### ISSUE TITLE
.native.js file extension are ignored

### ISSUE THREAD

**Issue by donovantc** [yahoo/babel-plugin-react-intl#102]
Should this plugin evaluate files within the evaluated directory that have the extension .native.js?

When I console log the files that are evaluated, all the .jsx and .js files are correctly evaluated but the .native.js are not evaluated at all. These files contain standard JSX and when I change the file extension to .js, they are correctly evaluated. However, due to our current setup, we would like to keep the extension .native.js and not change them to just .js

Does anyone perhaps have an idea how to get this plugin working so that .native.js files will also be evaluated?

Thanks

**Comment by ericf** [comment]
What do you mean by evaluated?

Are you sure Babel is processing the files?

**Comment by donovantc** [comment]
So, inside my .babelrc file I have the following properties for this plugin defined:

`"react-intl", {
        "messagesDir": "./",
        "enforceDescriptions": false
      }`

So this plugin will evaluate everything inside the directories inside my app (./). Which it does. I know this because I am getting .json files with the generated defined messages. However, if I have a file ending in .native.js within one of the directories inside my app (./) it simply ignores this file.

To verify, I added a console.log inside this plugins index.js file, inside the pre function of the traversal, which console logs the  filename being traversed. This logs all .js and .jsx files but not the .native.js files.

Does this plugin define which files to traverse or is babel decided that before this plugin executes?

**Comment by ericf** [comment]
Babel decides. That's why I was wondering if those `.native.js` files are being transformed by your other Babel plugins or if they are being completely ignored by Babel?

However you're kicking off Babel (task runner, cli, etc.) you probably need to provide some glob path to your source files, or define some root dir and a list of extension similar to `babel-register`'s config: https://babeljs.io/docs/usage/babel-register/#specifying-options

**Comment by donovantc** [comment]
That makes sense. Very useful info, I'll try that out. Thanks @ericf
