### ISSUE TITLE
How this plugin works?

### ISSUE THREAD

**Issue by sm2017** [yahoo/babel-plugin-react-intl#123]
I know this is duplicated issue , But I really don't know how it works

I do following
```
yarn add babel-plugin-react-intl --dev
```

# .babelrc
```
{
...
  "plugins": [
    ["react-intl", {
        "messagesDir": "./build/messages/"
    }]
  ]
...
}
```

And now? How to use it? I have `<FormattedMessage>` in my code , How extract string messages?

**Comment by Druux** [comment]
@sm2017 did you figure it out how to use it?

**Comment by sm2017** [comment]
@Druux Yes , Just install it and run you app using `react-native run-android` for example and go to `messagesDir` , You can see some generated files

**Comment by Druux** [comment]
@sm2017 unfortunately that doesn't work for me - the only way to generate the messagesDir is by executing `babel --plugins react-intl` for each .js file which includes a react-intl component....
nothing happens if I am calling `react-native run-ios`
