### ISSUE TITLE
Is this lib dead?

### ISSUE THREAD

**Issue by steida** [yahoo/babel-plugin-react-intl#124]
Sorry for the harsh question, but there is no update for more half year.

**Comment by okuryu** [comment]
I don't have a permission for this git repo, but it's same status as react-intl.

cc: @gyehuda @redonkulus

**Comment by steida** [comment]
Thank you for an answer. @gyehuda Can you please explain community what we can expect? Thank you.

**Comment by gyehuda** [comment]
I have granted @okuryu permissions for this repo (and others related to this). I understand that he's taking over some of the work that @ericf did in this space. The project is as alive as the community is interested in keeping it alive.
