### ISSUE TITLE
Not compatible with babel 6?

### ISSUE THREAD

**Issue by jlecomte** [yahoo/babel-plugin-react-intl#14]
I tried to upgrade babel to the latest major version (6) on my project, and it seems like this plugin is not compatible (?) Maybe this is obvious, but I don't see any compatibility note anywhere. Just wondering...

**Comment by ericf** [comment]
How do you lock down a Babel plugin to 5.x? Have you looked at how others are locking down? I haven't had a chance to do this yet. My plan is for 1.0 to support Babel 5, and 2.0 to support Babel 6. I just not sure how to lock down to Babel 5/6 via npm.

**Comment by jlecomte** [comment]
Isn't that what `peerDependencies` are for? Again, this may be naive. Worst case, it might be useful to write down a short note about compatibility in the README file. Thanks!

**Comment by hongrich** [comment]
If you are using webpack with Babel 6, it's also not compatible with this plugin. https://github.com/babel/babel-loader/issues/132#issuecomment-153155530

It seems like other babel plugins just bump their major version when they updated to support Babel 6 and make a note about compatibility.

**Comment by musbaig** [comment]
@ericf Is there an ETA for `v2.0` of this plugin for supporting Babel v6? We're running React-Intl v2 with Babel v6, and currently don't have any means of extracting messages for localization. Thanks!

**Comment by markuswaltre** [comment]
I am also interested in when 2.0 might be released as we are using Babel 6. Thanks!

**Comment by ericf** [comment]
I have a rewrite locally…still testing it out though.

**Comment by ericf** [comment]
PR #21 is a rewrite of the plugin to work with Babel 6.
