### ISSUE TITLE
Use the plugin with the babel API

### ISSUE THREAD

**Issue by enahum** [yahoo/babel-plugin-react-intl#15]
require('babel-core').transform("code", { 
           plugins: ["react-intl"], 
            modules: "amd", 
            filename: './temp/components/admin_console/admin_sidebar.jsx'
        });

If i use that code the plugin doesn't seem to work, the file.metadata.modules.imports on line 186 is an empty array so mightHaveReactIntlMessages var is always false.

@ericf were you able to actually run it without the babel-cli?

thanks.

**Comment by ericf** [comment]
Yup, it works for me. I tried it on [this example](https://github.com/yahoo/react-intl/tree/master/examples/translations) using the following script:

```js
var babel = require('babel-core');

var result = babel.transformFileSync('./src/client/components/app.js', {
    plugins: ['react-intl'],
    modules: 'amd',
});

console.log(result.metadata['react-intl']);

```
