### ISSUE TITLE
messagesObj.get(...).map is not a function

### ISSUE THREAD

**Issue by BenNG** [yahoo/babel-plugin-react-intl#16]
Hello, 

I try to test react-intl@2.0.0-beta-1 with babel-plugin-react-intl

I defined
```
import {defineMessages, injectIntl} from 'react-intl';
...
render(){
        const {formatMessage} = this.props.intl;

}
...
export default injectIntl(Serie)
formatMessage(messages.aa)
...
const messages = defineMessages({
    aa: {
        id: 'serie.aa',
        defaultMessage: 'travail',
    },
    bb: {
        id: 'serie.bb',
        defaultMessage: 'Temps',
    },
    cc: {
        id: 'serie.cc',
        defaultMessage: 'cycle',
    },
});

```
I use this .babelrc
```
{
  "plugins": ["react-intl"],
  "extra": {
    "react-intl": {
        "messagesDir": "./app/langs/",
        "enforceDescriptions": false
    }
  }
}

```

when I try to build I have this message: 
```
messagesObj.get(...).map is not a function
    at NodePath.CallExpression (/keep/Repo/burner-front/node_modules/babel-plugin-react-intl/lib/index.js:300:51)
....
```

sorry if it my bad it's the first time I use react-intl
cheers

**Comment by BenNG** [comment]
line 300 `messagesObj.get('properties')` seems to be an object instead of tan array

**Comment by ericf** [comment]
Which version of Babel?

**Comment by BenNG** [comment]
I'm using this version: 
    "babel": "^5.8.21",
    "babel-core": "5.6.15",
    "babel-loader": "5.2.2",

**Comment by ericf** [comment]
Can you create a basic reproducible example of this for me to try?

**Comment by BenNG** [comment]
Hi ! 

Well I tried on a brand new project and it works...

So In my project I just updated my babel* packages
"babel": "^5.8.21", --> deleted
"babel-core": "5.6.15" --> "babel-core": "^5.8.25",
"babel-loader": "5.2.2", --> same


Well ... sorry and thanks for your time ! 
Awesome project by the way :)))

**Comment by ericf** [comment]
Cool, glad you were able to fix the issue!
