### ISSUE TITLE
Why separate JSON files per component that uses FormattedMessage

### ISSUE THREAD

**Issue by esseb** [yahoo/babel-plugin-react-intl#2]
React Intl v2.0.0-pr-1 uses a flat message system, where `<FormattedMessage id="greeting" ...>` in `header.jsx` and `<FormattedMessage id="greeting" ...>` in `footer.jsx` refers to the same message.

In my application, I have this in `header.jsx`:
```
<FormattedMessage
  id="greeting"
  description="Welcome greeting to the user"
  defaultMessage="Hello, {name}! How are you today?"
  values={{name: 'this.props.name'}}
/>
```

In `footer.jsx` I have this:
```
<FormattedMessage
  id="greeting"
  values={{name: 'this.props.name'}}
/>
```

This works fine, although the `[React Intl] Line 16: Message "greeting" is missing a 'defaultMessage' and will not be extracted.` warning is a bit annoying since this is intentional.

`babel-plugin-react-intl` creates these two JSON message files:
* `./build/messages/app/components/header/header.json`
* `./build/messages/app/components/footer/footer.json` (this is empty)

Because of the flat message system, I don't see the point in separating the messages based on the owner components. I would expect that `babel-plugin-react-intl` instead created just one file: `./build/messages.json`

The problem here is, if I later decide to remove the message from `header.jsx` (which will require me to move `description` and `defaultMessage` to `footer.jsx`), the JSON file I need to give translators for translations jumped from `./build/messages/app/components/header/header.json` to `./build/messages/app/components/footer/footer.json`

I suppose I could always create a secondary step where I combine the various message JSON files myself, I just don't understand the `header.json` vs `footer.json` use case. I'd like at least an option to just create a single `messages.json` file.

**Comment by ericf** [comment]
The reason for one JSON per file that has messages defined (I can correct the empty file problem) is to not be lossy.

I originally had everything output to a single file, but it felt like a hack, especially since Babel currently processes one file at a time, and didn't provide a post processing step the info about where the messages were coming from (which files). So yeah, you can aggregate the files into one, my hope is that it's fairly straightforward for people to do — I'll likely add an example in this repo on how to, so people can copy+paste it. 

My recommendation is to use your React components as the reuse mechanism and only use a message in the file where it's defined.

**Comment by esseb** [comment]
> So yeah, you can aggregate the files into one, my hope is that it's fairly straightforward for people to do — I'll likely add an example in this repo on how to, so people can copy+paste it.

All right, that works for me. I'll do this.

> My recommendation is to use your React components as the reuse mechanism and only use a message in the file where it's defined.

You mean create for instance a `GreetingMessage` component and use it like `<GreetingMessage name={this.property.name} />`?

**Comment by ericf** [comment]
@esseb yes, but it doesn't have to be that granular, hopefully your components are such that larger chunks of your UI which declare messages are reused.

If you have the same string used in many places of your app, then another approach is to eschew co-location and use `defineMessage()` to define constants that are exported.

I'll think more about what you ran into and try to think of ways to improve it.

**Comment by esseb** [comment]
Ok, thanks for the insight. I'll think a bit about what makes sense for my application. I'll continue the discussion in https://github.com/yahoo/react-intl/issues/162 if needed.

**Comment by amccloud** [comment]
@ericf an example would be great. I'm confused about how to use the extracted results. The output of this plugin seems so far from the input of `react-intl#IntlProvider`.

**Comment by ericf** [comment]
@amccloud The format for IntlProvider's `messages` is `id: message`. Here's an example: https://github.com/yahoo/react-intl/issues/251#issuecomment-165863247

**Comment by nikglavin** [comment]
Sorry to revive the dead. @ericf you mentioned that you might provide an example of how to create a single file per language rather than mirroring the directory structure, do you still plan to do this ?

**Comment by oreqizer** [comment]
I'd be interested in this too
