### ISSUE TITLE
Module importing syntax

### ISSUE THREAD

**Issue by Joran182to** [yahoo/babel-plugin-react-intl#24]
Hello.
I found a restriction. I have 2 react components, one of them using 'Import' syntax:
```javascript
import {FormattedMessage} from 'react-intl';
```
And another one using 'require' syntax:
```javascript
const FormattedMessage = require('react-intl').FormattedMessage;
```
So, plugin extracts messages only from component with 'Import' syntax. Of course it's not a core, but might be useful for some cases.

**Comment by ericf** [comment]
Yeah, this plugin only supports the standard ECMAScript module import syntax, because imports must be static and top-level which makes the plugin simpler, more correct, and not rely on brittle heuristics.
