### ISSUE TITLE
Error while using with webpack

### ISSUE THREAD

**Issue by nmaves** [yahoo/babel-plugin-react-intl#25]
When I run webpack I get the following error.

```
ERROR in ./app/components/Home.js
Module build failed: SyntaxError: /Users/nmaves/projects/maves-software/intensity/app/components/Home.js: [React Intl] Message must have a `description`.
  2 | import {defineMessages, injectIntl, intlShape, FormattedMessage} from 'react-intl'
  3 | 
> 4 | const messages = defineMessages({
    |                  ^
  5 | 	greeting: {
  6 | 		id: 'greeting',
  7 | 		description: 'Welcome greeting to the user',
```

Here is my webpack.config.js

```
module.exports = {
	entry: "./app/App.js",
	output: {
		filename: "public/bundle.js"
	},
	module: {
		loaders: [
			{
				test: /\.jsx?$/,
				exclude: /(node_modules|bower_components)/,
				loader: 'babel',
				query: {
					presets: ['react', 'es2015'],
					plugins: ['react-intl']
				}
			}
		]
	}
}
```

Here is my test component.

```
import React from 'react'
import {defineMessages, injectIntl, intlShape, FormattedMessage} from 'react-intl'

const messages = defineMessages({
	greeting: {
		id: 'greeting',
		description: 'Welcome greeting to the user',
		defaultMessage: 'Hello, {name}! How are you today?'
	}
});

class Home extends React.Component {

	constructor(props) {
		super(props);
		this.state = {}
	}

	render() {
		return (
			<div>
				<FormattedMessage {...messages.greeting} />
			</div>
		)
	}
}

export default Home;
```

**Comment by emmenko** [comment]
I see you are getting the same error as I reported here #26

**Comment by nmaves** [comment]
Do you have a way around this bug?  Is there a setup with older versions that I could use?

**Comment by ericf** [comment]
The other time this issue was reported the person was running the react-intl Babel plugin multiple times. You should investigate whether multiple Babel config are being merged together, causing two runs of babel-plugin-react-intl.

The Webpack Babel Loader likely merges your .babelrc with what's in your webpack.config.js. If you want something custom in your Webpack build you should make sure to set it to not use the .babelrc file as well.

**Comment by emmenko** [comment]
@ericf Hmm, I'm not using webpack for this task and I don't think I'm running the plugin multiple times. Maybe you [can have a look](https://github.com/emmenko/redux-react-router-async-example/tree/babel-6) at yourself (the `babel-6` branch)?

I have one `.babelrc` file 
https://github.com/emmenko/redux-react-router-async-example/blob/babel-6/.babelrc

And this is the task I'm running 
https://github.com/emmenko/redux-react-router-async-example/blob/babel-6/package.json#L17 

Do you see anything strange there? Thanks.

**Comment by ericf** [comment]
You're running the plugin twice. It's loaded via .babelrc _and_ in the command line `--plugins` option.

**Comment by emmenko** [comment]
Ooh I see, I thought the `plugins` option was something else. Thanks! :)

**Comment by iam-peekay** [comment]
@ericf do you have an example using Webpack? it looks like all the examples in react-intl repo are using browserify. I'm a little confused on the build pipeline / configuration using webpack.

**Comment by iam-peekay** [comment]
@ericf to be more clear, I've got the exact .babelrc configuration as what's shown in the [docs](https://github.com/yahoo/babel-plugin-react-intl) but when I run webpack, nothing gets created in the target location. 

.babelrc
```
{
  "presets": ["react", "es2015", "stage-0"],
  "compact": false,
  "env": {
    "development": {
      "plugins": [
        ["react-transform", {
          "transforms": [{
            "transform": "react-transform-hmr",
            "imports": ["react"],
            // this is important for Webpack HMR:
            "locals": ["module"]
          }]
        }],
      ]
    }
  },
  "plugins": [
    ["react-intl", {
        "messagesDir": "./app/frontend/.config/i18n",
        "enforceDescriptions": false
    }],
  ]
}
```
