### ISSUE TITLE
The plugin "react-intl" didn't export a Plugin instance

### ISSUE THREAD

**Issue by Dindaleon** [yahoo/babel-plugin-react-intl#27]
I tried to configure it via `.babelrc` file, via webpack and node api, I followed the instructions on the README file, but I always get the same error:

    The plugin "react-intl" didn't export a Plugin instance

**Comment by ericf** [comment]
I couldn't say without more information. Be sure to follow the README instructions for Babel 5 vs 6.

**Comment by isTravis** [comment]
I had the same issue. I was using v1.0.0 with Babel 5 and following the Readme. As ericf points out, there are configs for babel 5 vs babel 6 (though only babel 6 version is shown on the main README).The default README is describing the setup for v2.0.0 and babel6, as babel 5 has a different way of managing .babelrc plugin definition.

If you look at the README during the 1.0.0 release [https://github.com/yahoo/babel-plugin-react-intl/tree/cced36eb33d71634e376dbc41559bde7dca11586](https://github.com/yahoo/babel-plugin-react-intl/tree/cced36eb33d71634e376dbc41559bde7dca11586), you'll notice a different .babelrc configuration. 

For v1.0.0 and babel v5, the following worked for my .babelrc: 

    {
      "plugins": ["react-intl"],
      "extra": {
        "react-intl": {
            "messagesDir": "./build/messages/",
            "enforceDescriptions": true
        }
      }
    }

Using that one fixed the `didn't export a Plugin instance` problem for me and got things working!

**Comment by ericf** [comment]
@isTravis thanks for providing this explanation.
