### ISSUE TITLE
Does this plugin work?

### ISSUE THREAD

**Issue by BradHarris** [yahoo/babel-plugin-react-intl#3]
`THIS IS A PREVIEW RELEASE THAT WORKS WITH A FUTURE, UNRELEASED VERSION OF REACT INTL.`

Does that mean react-intl v2.0.0-pr-1? Or some other unreleased version?

Nothing I do seems to make this plugin work on react-intl v2.0.0-pr-1.

**Comment by ericf** [comment]
Yes it works with `react-intl@2.0.0-pr-1`. Did you base what you're doing on the [example app](https://github.com/yahoo/react-intl/tree/master/examples/translations)?

**Comment by BradHarris** [comment]
Thanks for the link to the example app! I did not see this before. I have everything working and it works so well!
