### ISSUE TITLE
Translation files aren't being created

### ISSUE THREAD

**Issue by driesvancraen** [yahoo/babel-plugin-react-intl#34]
Hi,

I don't know if I'm implementing this wrong.
But I've set a .babelrc file, and I'm calling a FormattedMessage in the app, wrapped with a IntlProvider.
As I understand this should create the translation file in de defined folder?
Is there anything I'm forgetting?

`{
    "presets": [
        "es2015",
        "react"
    ],
    "plugins": [
        ["react-intl", {
            "messagesDir": "./src/messages/"
        }]
    ]
}`

**Comment by ericf** [comment]
Which version of the plugin are you using? v1 works with Babel 5, v2 works with Babel 6.

**Comment by Kureev** [comment]
I think I know an answer on this :wink: 
@driesvancraen, you're using react-native, right? In this case your packager's root would be a "base" dir of the relative path. 

Some insights for @ericf:
While using react-native, most people using `react-native run-<platform>` to run an application on emulator. It triggers running console with the following command:
```
$ path/to/folder/node_modules/react-native/packager/packager.sh start
```
which means that your babel plugin will detect `packager` folder as a "root". I don't know if it's possible to get an active `.babelrc` path, but if it's possible and you know how to do it - I can compose a PR to fix this behavior.

**Comment by BradHarris** [comment]
Hey,

I just spent the last 2 days trying to figure out why my webpack/babel configuration was only generating translation files sometimes and other times nothing!

It was because of the `cacheDirectory = true` in my babel-loader query. My solution was to use an environment variable set in my npm script to explicitly enable that flag when developing and default it to being disabled.

```
const CACHE_DIR = process.env.CACHE_DIR === 'true' ? true : false;
...
	loader: 'babel-loader',
	query: {
		cacheDirectory: CACHE_DIR,
		babelrc: true
	},
...
```

and my npm scripts looks something like:
```
"dev": "cross-env CACHE_DIR=true node app.js",
"build:lang-bundle": "rm -rf ./locales/build && npm run webpack"
```

I hope this helps anyone with similar issues.

**Comment by ericf** [comment]
I'm unsure of what action to take on this issue. Should this be closed because the issues you guys are talking about seem orthogonal?

**Comment by BradHarris** [comment]
Do what is in your heart, @ericf. I can't account for @driesvancraen issues, but I have solved mine. Also it has been more than a month with no update from @driesvancraen so maybe all is well?

**Comment by reergymerej** [comment]
@Kureev thanks for pointing me in the right direction.  After some low-tech debugging, I found my messages being created in `node_modules/react-native/messages/`.

## Quick Fix

`messagesDir` appears to be relative to `react-native`.  This config works as I expected.

```
      ["react-intl", {
        "messagesDir": "../../messages"
      }]
```

**Comment by rimzici** [comment]
@Kureev and @reergymerej Thanks for helping me figure out the issue and find a working solution.
@reergymerej  suggestion might still not work for react-native dev's using ubuntu, even in mac when packager is started manually. Would be better to have a reliable solution.

To go little more detailed, in mac usually packager will get started automatically with either of the commands.
`react-native run-android` or `react-native run-ios`
during this case `.babelrc` detects path `'project/node_modules/react-native/'` as root dir. And strings are extracted into this directory.


Now the packager can also be started by any of the following commands(usually the case in ubuntu)
```
react-native start
yarn start
npm start
```
with the following in package.json
```
"scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start"
 }
```
And now the root dir is `'project/'`, where the strings are extracted.

Thank You.
