### ISSUE TITLE
Does the plugin overrides already changed json files?

### ISSUE THREAD

**Issue by pke** [yahoo/babel-plugin-react-intl#39]
How does the plugin behave if there is already an translation file? Will it merge the existing json entries with new ones and not override already translated texts?

**Comment by ericf** [comment]
It would overwrite them, the idea is that you **wouldn't** checkin JSON files to source control, but instead treat them like built files and clear them out before running Babel on your source code.

**Comment by pke** [comment]
Uhm, where would u then make the actual translations? Confused 😖

**Comment by ericf** [comment]
You'd likely want to aggregate and process the JSON files into say an `en.json`, that you checkin. Then have your translation system work on those default strings, and then commit their results back to your project. If you don't aggregate them, old strings will still be included.

But to answer your direct question: the plugin uses overrides a file if it exists.

**Comment by GertjanReynaert** [comment]
@pke Maybe this can help? https://github.com/GertjanReynaert/react-intl-translations-manager

**Comment by pke** [comment]
@GertjanReynaert yes it does. Will check it out, thanks!
