### ISSUE TITLE
Plugin 0 specified in ....  provided an invalid property of "addLocaleData"

### ISSUE THREAD

**Issue by iamadit** [yahoo/babel-plugin-react-intl#40]
Getting this error when I add the plugin to do extraction

```
Module build failed: Error: Plugin 0 specified in "/...../web-react/.babelrc" provided an invalid property of "addLocaleData"
```

My `.babelrc` currently looks like this:

```
{
	presets: ['react', 'es2015', 'react-hmre', "stage-0"],
	"plugins": [
		["react-intl", {
			"messagesDir": "./build/lang/",
			"enforceDescriptions": true
			}
		]
	]
}
```

**Comment by marcelloromanelli** [comment]
@iamadit I'm getting the same exact error. Did you manage to solve it?

**Comment by mkontula** [comment]
Same error here with babel-plugin-react-intl 2.1.2, react-intl 2.1.1 and babel-cli 6.7.7. What are we doing wrong?

**Comment by ericf** [comment]
Do any of you want to provide a very simple reproducible example that I can run to see the problem?

**Comment by syko** [comment]
I ran into the same error but then I remembered I had just removed `babel-plugin-react-intl`. Reinstalling it helped a lot.

**Comment by marcelloromanelli** [comment]
@ericf my use case was this: https://github.com/juanda99/react-redux-starter-kit 
Cloned the repo, `npm i`, ` npm run build:i18n` and then the error. Let me know if that helps.

**Comment by ericf** [comment]
This is because that starter kit **doesn't actually install this package.**

**Comment by mkontula** [comment]
Updating to plugin v2.1.3 and react-intl v2.1.2 solved this to me. I'd still stay there _was_ an issue with one feature version before. Everything working as it should atm so I'm resting my case. Keep up the good work!
