### ISSUE TITLE
Required defaultMessage

### ISSUE THREAD

**Issue by tkislan** [yahoo/babel-plugin-react-intl#43]
What is the reason behind requiring the "defaultMessage" field when extracting the strings?
React-Intl can work perfectly fine without this attribute.

Would it be feasible to have an option/parameter for plugin not to require it if specified?
I could do it, and create a PR.

**Comment by ericf** [comment]
What's the use case you have where you're running up against this requirement?

The whole point of this plugin is to extract the `defaultMessage` from the source code. Otherwise there's nothing to extract.

**Comment by ericf** [comment]
I think it should be a bug if you're using `defineMessages()` _without_ providing a `defaultMessage` on each [Message Descriptor](https://github.com/yahoo/react-intl/wiki/API#definemessages), _and_ you're using this plugin to extract those default message strings.

**Comment by tkislan** [comment]
We are developing a smaller project, where the developers are also the translators. And therefore we don't require the `defaultMessage` to be available in translation files. All we need are msgIds and optionally a description.
Having a `defaultMessage` in the source code would cause having translations in 2 different places (in source code and in translation files).
From my point of view, whole point of this plugin is to have (primarily) the `id` of translation extracted. `defaultMessage` should only be a hint for translator.

**Comment by tkislan** [comment]
Looking through the react-intl code, `defaultMessage` is not strictly required. It is only used, when an actual translation is not found, and even then, if not provided, it produces warning, and uses `id` as a fallback. Which is a normal behaviour with all gettext implementations.

**Comment by ericf** [comment]
The `defaultMessage` is the original string for the default language of the app. The `description` is the note to the translator.

The idea with this plugin is to author your default language strings _in_ your React source files, and use this plugin to extract them and have the extracted files run through whatever translation process you have.

The translated files are then passed into `<IntlProvide>` at runtime in a simple `{"messageId": "translated message"}` collection.

**Comment by pigoz** [comment]
In some workflows its useful to not have default messages in code. For example we have a file that's editable by non developers to edit our strings for both translations and the 'main' language (and it's the source of truth).

Would you accept a patch with an option to relax the requirement?

**Comment by ericf** [comment]
@pigoz that's already supported. Simply don't add those to `defineMessages()` and/or don't include `defaultMessage` prop when using `<FormattedMessage>`, just use an `id`.

**Comment by pigoz** [comment]
@ericf when using only `id` as a `<FormatMessage>` attribute it looks like this babel plugin ignores it. As soon as I add a defaultMessage, the message got extracted. So not sure, maybe I am triggering a bug.

If this is indeed supposed to work, I can check again. Meanwhile I wrote a very simple babel plugin to extract only the ids from my JSX code.

**Comment by ericf** [comment]
This plugin only extracts `defaultMessage`s, if there's no default translation to extract, then this doesn't do anything.

What's the reason you want to extract only the ids?

**Comment by pigoz** [comment]
As I mentioned the equivalent of our `defaultMessage`s source of truth is stored outside of the codebase. This works really well for us because non-tech people can edit marketing text, for this reason we only use the id on FormatMessage.

I want to extract the ids so I can create automated reports of unused and untraslated strings (diffing them against the source of truth's ids).

**Comment by ericf** [comment]
@pigoz okay, feel free to propose a PR for this feature. I think it should probably include an option that's disabled by default.

**Comment by Floriferous** [comment]
I really dislike the `defaultMessage` functionality. It makes collaboration between developers and non-developers on the main language impossible, as I can't grant them access to our code to modify a few strings here and there.

Having this feature would be great.
