### ISSUE TITLE
Messages are not always picked up

### ISSUE THREAD

**Issue by benzen** [yahoo/babel-plugin-react-intl#47]
I managed to get this plugin work a first time.

Add translation was good, the messages keep poping in my './messages/' folder.
Then i decided to remove the folder, and let  babel recreate the messages for me.
In this scenario, the messages are not recreated.
I had to go through all the component, make a change in order for the message to be extracted.

I guess this issue depends on the way I use babel any advice on where to look.
If we found something, it could be added as a warning in the readme/relevant docs

**Comment by benzen** [comment]
As often, talking about a problem help.

I found that this issue is caused by my config of webpack's babel-loader.
I had to go from this

      {
        test: /.jsx?$/,
        loader: 'babel-loader?cacheDir',
        exclude: /node_modules/,
      },

to 

      {
        test: /.jsx?$/,
        loader: 'babel-loader?cacheDirectory&cacheIdentifier='+ Math.random(),
        exclude: /node_modules/,
      },

Note that 

        loader: 'babel-loader'

Would also do the trick, but it will give you slower build

**Comment by ericf** [comment]
This makes sense since you're telling `babel-loader` to keep a cache around — doing this probably only makes sense in development and shouldn't be used for your prod build.

Since the messages JSON files are derivative they aren't part of the cache key. Not too sure there's a good way around this.

**Comment by ericf** [comment]
@benzen There's a similar discussion here that has more info that you might be able to use: https://github.com/Ognian/react-intl-webpack-plugin/issues/1

**Comment by enzoferey** [comment]
For Next.js:

https://github.com/yahoo/babel-plugin-react-intl/issues/160#issuecomment-449004343
