### ISSUE TITLE
TypeScript

### ISSUE THREAD

**Issue by googol7** [yahoo/babel-plugin-react-intl#48]
It would be very nice, if the tool also worked together with TypeScript.

**Comment by ericf** [comment]
Please say more…

**Comment by googol7** [comment]
In [https://github.com/yahoo/react-intl/issues/162](https://github.com/yahoo/react-intl/issues/162) you said:

> I only have plans to officially support the Babel plugin for extracting the default messages from source so they can be prepared for translation. It looks like you could have the TypeScript compiler output ES6 via the --target ES6 option, and then you could use Babel to transpile to ES3/5. It would be adding to your toolchain, but could open up your code base to more static analysis and tooling outside of what TypeScript provides.

It would be very nice though if "typescript-plugin-react-intl" could directly extract messages from TypeScript *.ts and *.tsx files.

**Comment by ericf** [comment]
Okay, but that's not something I will be writing.

**Comment by googol7** [comment]
at the moment my script makemessages.sh looks like this:

```
#!/bin/bash
rm -rf trans-tmp extracted-messages
node_modules/.bin/tsc -p . --target ES6 --module es6 --jsx preserve --outDir trans-tmp
node_modules/.bin/babel --plugins react-intl "trans-tmp/**/*.jsx"
```

**Comment by davidjsalazarmoreno** [comment]
Thank you @googol7, your script works for me.

**Comment by googol7** [comment]
I’m also using [react-intl-translations-manager](https://github.com/GertjanReynaert/react-intl-translations-manager) now. So my script `makemessages.sh` now looks like this:

```
#!/bin/bash
rm -rf trans-tmp extracted-messages
node_modules/.bin/tsc -p . --target ES6 --module es6 --jsx preserve --outDir trans-tmp
node_modules/.bin/babel --plugins react-intl "trans-tmp/**/*.jsx"
npm run manage:translations
```

package.json contains:
```
  "scripts": {
    "manage:translations": "node_modules/.bin/babel-node ./translationRunner.js"
  },
```

`translationRunner.js` looks like this:
```
import manageTranslations, { readMessageFiles, createSingleMessagesFile } from "react-intl-translations-manager"

const messagesDir = "extracted-messages"
const translationsDir = "src/app/l10n/"
const singleMessageFileDir = "."

manageTranslations({
    messagesDirectory: messagesDir,
    translationsDirectory: translationsDir,
    languages: ["en", "cs", "de", "es", "fr", "it", "ja"],
})

const extractedMessages = readMessageFiles(messagesDir)

createSingleMessagesFile({
    messages: extractedMessages,
    directory: singleMessageFileDir,
    jsonSpaceIndentation: 4,
})
```
