### ISSUE TITLE
messagesObj.get(...).map is not a function AGAIN

### ISSUE THREAD

**Issue by dnutels** [yahoo/babel-plugin-react-intl#49]
It seems to me there is some fishy parsing going on....

> I don't think https://github.com/yahoo/babel-plugin-react-intl/issues/16 is fixed, BTW.

**.babelrc**

```
{
    "plugins": [
        ["react-intl", {
            "messagesDir": "./dist/i18n/",
            "enforceDescriptions": true
        }]
    ]
}
```

**If I do this:**

```
import {defineMessages} from 'react-intl';

const messages = defineMessages({
    anotherText: {
        id: 'anotherText',
        description: 'Some Text',
        defaultMessage: 'Some Text with {title}!'
    },
    yetAnotherText: {
        id: 'yetAnotherText',
        description: 'Yet Another Text',
        defaultMessage: 'Yet Another Text with {title}!'
    }        
});

console.log(messages);
```

everything works absolutely fine.

**If I do this:**

```
import {defineMessages} from 'react-intl';

const messages = {
    anotherText: {
        id: 'anotherText',
        description: 'Some Text',
        defaultMessage: 'Some Text with {title}!'
    },
    yetAnotherText: {
        id: 'yetAnotherText',
        description: 'Yet Another Text',
        defaultMessage: 'Yet Another Text with {title}!'
    }        
};

console.log(defineMessages(messages));
```

then `babel-plugin-react-intl` throws this:

```
messagesObj.get(...).map is not a function
    at PluginPass.CallExpression (<ABRIDGED>\node_modules\babel-plugin-react-intl\lib\index.js:208:51)
```

**Direct copy/paste from `package.json`**

```
{
  "devDependencies": {
    "babel-core": "^6.7.6",
    "babel-plugin-react-intl": "^2.1.2",
    "babel-preset-react": "^6.5.0",   
    "react-intl": "^2.1.2"
}
```

I am a bit puzzled.

**Comment by ericf** [comment]
This isn't supported. Usually there's an error saying so, but looks like something is erroring out before hand. To simplify the plugin from needing to trace code, you must pass an object literal to `defineMessages()`.

**Comment by dnutels** [comment]
I imagine that there is some static code analysis/parsing going on...

**What would be an alternative, as you can clearly see that this is a big big issue?**

Imagine having to customize the messages bundle for a component. Normally you'd get the original bundle, merge it with the customizing one and feed it to the `defineMessages`. **You can't.**

**Comment by ericf** [comment]
> as you can clearly see that this is a big big issue?

I don't understand what you're trying to do and why you can't declare your messages in the call to `defineMessages()`?

You're merging can happen when you pass things into `<IntlProvider>`, not at code authoring time.

**Comment by dnutels** [comment]
Alright.

Imagine you having a component. One that you write and then provide for others to use. This happens within a large company.

As part of you are trying to achieve, aside from providing a piece of business functionality for other to use, is an ability to alter the behavior and presentation of your component.

Basically allow someone else to customize your component. It may be a simple override of a class's method (it is an React ES6 class, for instance). It may be replacing some inner component via Webpack.

Or, it may be changing the texts, if your messages are exposed via re-export, so that someone may re-compose them into their component, one that extends yours:

```
import messages from './some/path/or/may/be/npm/module/Component.i18n';
import Component from './some/path/or/may/be/npm/module/Component';

...
export myMessages;
export default MyComponent extends Component {
    
    ...

    render() {
        <div>
            <FormattedMessage {...myMessages.someMessage} />
        </div>
    }

    ...
    
}
```

How simple it would be if I could do this:

```
const myMessages = defineMessages({
    ...messages,
    someMessage: {
        ...
    }
});
```

**Alas.**

Instead, you would expect me to add an additional, nested `IntlProvider` that would then inject it, via React Context.

That seems absolutely counter-intuitive to me. Especially considering that `defineMessages` API doesn't work how you would expect a JavaScript API to behave, where passing object literal "inline" is expected to work the same as passing a reference to a previously contructed object.

**Comment by ericf** [comment]
> That seems absolutely counter-intuitive to me. Especially considering that defineMessages API doesn't work how you would expect a JavaScript API to behave, where passing object literal "inline" is expected to work the same as passing a reference to a previously contructed object.

Correct. You can appreciate the complexity of making a static analysis tool work for your dynamic case which __isn't static.__ It would have to implement the core of [Flow](http://flowtype.org) within this Babel plugin to accomplish that.

You could think of customizing messages the same as providing customized translations of messages via `<IntlProvider>`. The solution to use (at a large company) is nested `<IntlProvider>` instances to pass a component in another package its messages.

This is part of a larger discussion that you should check out here: https://github.com/yahoo/react-intl/issues/419

One thing to consider about _generic_ reusable components is whether they should contain their own strings, or just have slots in the UI that they fill in with props: https://github.com/yahoo/react-intl/issues/419#issuecomment-213841978

**Comment by dnutels** [comment]
You'd be correct, with the `props` comment, if we were talking about pure UI components. 

These are not. 

They actually, in Redux vernacular, are Container components and they are the ones that pass messages, via props, to their pure UI Component children.

I will follow the discussion as suggested.

**Comment by ericf** [comment]
https://github.com/yahoo/react-intl/tree/master/examples/nested

**Comment by ericf** [comment]
If you control all of the packages that contain UI components/containers, the simplest approach is to namespace all of your message ids per package, then aggregate all their strings together and build-time and pass in the whole collection to the root `<IntlProvider>` and use only one instance.

**Comment by ericf** [comment]
This discussion should move to the React Intl repo. I'm going to take care of the original bug in the error message and close this.

**Comment by dnutels** [comment]
OK. Thank you.

Last note....

> then aggregate all their strings together and build-time 

I thought this is what this plugin is supposed to do.

**Comment by ericf** [comment]
The plugin only runs on the files you process through Babel at the time you compile. If you have multiple packages, you'll likely be compiling those at different times, right before each one is published.

**Comment by dnutels** [comment]
Forgive me if this seems as badgering, but that is an absolutely incorrect assumption.

In most cases the process will go like that:

1. someone develops a module **in React/ES6** that represents a chunk of business functionality 
2. he/she publishes it to on-premises npm
3. an **application** (and normally there are several), also React/ES6, consumes it along with other similar modules

It is at the time of **application** packaging/build that you want to process those messages. Creating translation bundles on per-module basis is very very unlikely and nearly impossible on a larger scale.

**Comment by ericf** [comment]
As part of the build process for each package, have it include a `messages.json` which aggregates all of that package's default messages extracted from its components into one file. With this convention, your app can walk all the packages and gather their `messages.json` file, aggregate them once again, and send them through the translation process.

If each package name-spaces its message ids, then there shouldn't be any conflicts. And you can provide any overrides at the app-level.

In any case, this is outside the scope of this package. This package simply extracts the strings defined **statically** in your JavaScript source code. It's up to whatever process you come up with on how to process those extracted strings. `defineMessages` is [literally "echo"](https://github.com/yahoo/react-intl/blob/54d40377e1f6c2daf27030a8a5cda4cd2530060e/src/define-messages.js) it's an export used to provide a hook for this plugin to process the **statically** defined messages.

I suggest you figure out with other people in your company how you want to architect your translation pipeline between all your separate packages.
