### ISSUE TITLE
Infinite mkdirp loop when coming from another Webpack loader

### ISSUE THREAD

**Issue by dallonf** [yahoo/babel-plugin-react-intl#5]
In my setup, I have [ts-loader](https://github.com/TypeStrong/ts-loader) set to run before babel-loader. When I add a reference to `FormattedMessage` to a file (say `Page.tsx`), it looks like it assumes the filename (specifically `file.opts.filename`, which I found by placing some strategic `console.log`s in the `exit()` method in this plugin) is `[project dir]/node_modules/ts-loader/index.js![project dir]/src/pages/asset/Page.tsx'`. The plugin then proceeds to try to create a folder at that nonsense URL  and maxes out the stack.

Does it make sense for this plugin to be aware of the Webpack/loaders case (I think JSPM has a similar syntax)? Or maybe `babel-loader` should be passing more realistic filenames and I should go create an issue on that project? Either way, this is a blocker to me being able to use this plugin, which had been extremely useful before I switched to TypeScript!

**Comment by ericf** [comment]
Does `file.opts` contain any real paths in your setup?

**Comment by dallonf** [comment]
Unfortunately not; I did a quick console.log to see what was inside (sorry for the bizarre whitespace, the terminal formatted it strangely)

```{ filename: '[project directory]/node_modules/ts-loa
der/index.js![project directory]/src/pages/asset/Page.tsx',   
  filenameRelative: '[project directory]/node_modules/ts-loade
r/index.js![project directory]/src/pages/asset/Page.tsx',     
  inputSourceMap: undefined,    
  extra:      
   { 'react-transform': { transforms: [Object] }, 
     'react-intl': { messagesDir: './.intl-output' } },    
  env: {},    
  moduleId: undefined, 
  getModuleId: undefined,       
  retainLines: false,  
  nonStandard: true,   
  experimental: false, 
  highlightCode: true, 
  suppressDeprecationMessages: false,    
  resolveModuleSource: undefined,        
  stage: 1,   
  blacklist: [ 'regenerator', 'regenerator' ],    
  whitelist: undefined,
  optional:   
   [ 'asyncToGenerator',        
     'es7.functionBind',        
     'es7.classProperties',     
     'runtime' ],      
  modules: 'common',   
  moduleIds: false,    
  loose: undefined,    
  jsxPragma: 'React.createElement',      
  plugins: [ 'react-transform', 'react-intl' ],   
  ignore: [], 
  only: undefined,     
  code: true, 
  metadata: true,      
  ast: true,  
  comments: true,      
  shouldPrintComment: undefined,
  compact: 'auto',     
  keepModuleIdExtensions: false,
  auxiliaryComment: undefined,  
  auxiliaryCommentBefore: undefined,     
  auxiliaryCommentAfter: '',    
  externalHelpers: false,       
  metadataUsedHelpers: false,   
  sourceMap: true,     
  sourceMaps: true,    
  sourceMapName: undefined,     
  sourceMapTarget: '[project directory]/node_modules/ts-loader
/index.js![project directory]/src/pages/asset/Page.tsx',      
  sourceFileName: '[project directory]/node_modules/ts-loader/
index.js![project directory]/src/pages/asset/Page.tsx',       
  sourceRoot: undefined,        
  moduleRoot: undefined,        
  breakConfig: false,  
  babelrc: undefined,  
  sourceType: 'module',
  basename: 'Page' }   
```

**Comment by ericf** [comment]
Is `[project directory]` a redaction, or is it literally there?

Does `babel-loader` do something special when it encounters file paths with `!`?

**Comment by dallonf** [comment]
`[project directory]` is my edit, sorry for the confusion! I'm not sure what babel-loader should be doing in this case. It's starting to sound like the problem is there, though? Babel plugins probably shouldn't need to be aware of the terrible things Webpack can do to filepaths.

**Comment by dallonf** [comment]
I'm gonna go ahead and close this issue since it's not really a problem with this plugin.

**Comment by ericf** [comment]
Okay, makes sense. But please post back here if you think out a root cause and/or solution.
