### ISSUE TITLE
No extraction without warning

### ISSUE THREAD

**Issue by benzen** [yahoo/babel-plugin-react-intl#52]
If I define a message like this

    <FormattedMessage id="hello">

The message will be used in the app, but the babel plugin will not warn about anything (which make defaultMessage not required) this comportement is not necessary bad in my opinion, because i always use the same value for id and defaultMessage.

What is a bug, is that the babel plugin will see the message but ignore it and will not extract the message.

**Comment by ericf** [comment]
This is allowed because messages might be passed into `<IntlProvider>` that won't be extracted via this plugin; e.g., legacy strings, or top-level product strings defined outside of any React components.

https://github.com/yahoo/babel-plugin-react-intl/blob/master/src/index.js#L206-L215
