### ISSUE TITLE
Getting an error when iterating over messages

### ISSUE THREAD

**Issue by NSLS** [yahoo/babel-plugin-react-intl#56]
Hello. I am writing an application using react-intl and babel-plugin-react-intl for extracting messages, as it is intended.
However, the code below breaks build with an error "[React Intl] Messages must be statically evaluate-able for extraction."

`const keys = [
			'some',
			'other',
			'thing'
		];`
```
const messages = keys.map((item, key) => {
	return (<FormattedMessage key={key}
		description="Sample description"
		id={item}
		defaultMessage={item}
	/>);
});
```

Whilst code like this - doesn't

```
const key = 'some';

<FormattedMessage
	description="Sample description"
	id={key}
	defaultMessage={key}
/>
```

I am very confused with such behaviour and would like to hear some possible solutions for this. Thanks.

**Comment by ericf** [comment]
Babel has a feature to evaluate statements statically, but it's not a full JS interpreter so it can only handle simple cases like the second one you showed and not more complex ones like the first.

For cases like this, you should use [`defineMessages`](https://github.com/yahoo/react-intl/wiki/API#definemessages):

```js
const messages = defineMessages({
  foo: {
    id: 'foo',
    defaultMessage: 'Foo',
  },
  bar: {
    id: 'bar',
    defaultMessage: 'Bar',
  },
});

const messageElements = Object.keys(messages).map(key => (
  <FormattedMessage
    key={key}
    {...messages[key]}
  />
));
```

**Comment by NSLS** [comment]
Very helpful, thanks!
