### ISSUE TITLE
Delete JSON file with extracted messages if component with message definitions was deleted

### ISSUE THREAD

**Issue by yrypka** [yahoo/babel-plugin-react-intl#58]
Is there a way to delete automatically JSON file with extracted from React component messages if that component was deleted/renamed?

This is a bit annoying to go and remove JSON files manually every time I remove or rename a component. And it's easy to forget to do that.

I thought that the problem was in my Babel configuration saying to cache output into the file system but it looks like that's not the case.

Has anybody encountered this problem?

**Comment by ericf** [comment]
Are you cleaning/removing out the messages dir before you run Babel?

**Comment by yrypka** [comment]
Actually, no. I considered that as a potential approach to resolving this issue, but I thought that should be `babel-plugin-react-intl`'s responsibility to handle that.

**Comment by ericf** [comment]
Why's that? This is similar if you compiled a project's `src/` dir to `build/` with Babel, removed a src file and wanted it to be removed from the build dir. Since the build files are derived from the src files, it seems all you need to do is run a clean build to get what you want.

**Comment by yrypka** [comment]
Fair enough. That makes sense. Thanks for your help.
