### ISSUE TITLE
Unable to use with a higher order component (HOC)

### ISSUE THREAD

**Issue by rosskevin** [yahoo/babel-plugin-react-intl#59]
I find the `react-intl` a bit too verbose for my usage so I'm looking at options.

## HOC workaround
To start, I made a really simple shortcut component to shorten usage:

```javascript
// @flow
import React from 'react'
import {FormattedMessage} from 'react-intl'
import pure from 'recompose/pure'

type MProps = {v?:Object, id: string, m:string}
const M = pure((props:MProps):Element<any> => {
  const { v, m, ...rest } = props
  return <FormattedMessage values={v} defaultMessage={m} {...rest} />
})

export {
  M
}
```

This takes:

```javascript
<FormattedMessage id="greeting"
      defaultMessage="Hello, {name}! How are you today?"
      values={{name: this.props.name}}
      />
```

and shortens it to:

```javascript
<M id='greeting' v={{name: this.props.name}} m='Hello, {name}! How are you today?' />
```
Certainly shorter (even if crytpic) but significantly reduces the size of my page component markup by allowing me to use a single line in many cases.

## Error

The problem as you may have already guessed is that this babel plugin will not pickup the messages and generate the json file, it yields:

```
client?80c2:47 ./ui/src/lib/ui/i18n.js
Module build failed: Error: /Users/kross/projects/af_core/ui/src/lib/ui/i18n.js: [React Intl] Messages must be statically evaluate-able for extraction.
SyntaxError: /Users/kross/projects/af_core/ui/src/lib/ui/i18n.js: [React Intl] Messages must be statically evaluate-able for extraction.
  15 | const M = pure((props:MProps):Element<any> => {
  16 |   const { v, m, ...rest } = props
> 17 |   return <FormattedMessage values={v} defaultMessage={m} {...rest} />
     |                                                       ^
  18 | })
  19 | 
  20 | export {
    at File.buildCodeFrameError (/Users/kross/projects/af_core/node_modules/babel-core/lib/transformation/file/index.js:446:15)
    at NodePath.buildCodeFrameError (/Users/kross/projects/af_core/node_modules/babel-traverse/lib/path/index.js:143:26)
    at getMessageDescriptorValue (/Users/kross/projects/af_core/node_modules/babel-plugin-react-intl/lib/index.js:55:20)
    at /Users/kross/projects/af_core/node_modules/babel-plugin-react-intl/lib/index.js:76:25
    at Array.reduce (native)
    at createMessageDescriptor (/Users/kross/projects/af_core/node_modules/babel-plugin-react-intl/lib/index.js:64:26)
    at PluginPass.JSXOpeningElement (/Users/kross/projects/af_core/node_modules/babel-plugin-react-intl/lib/index.js:189:38)
    at newFn (/Users/kross/projects/af_core/node_modules/babel-traverse/lib/visitors.js:301:19)
    at NodePath._call (/Users/kross/projects/af_core/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/kross/projects/af_core/node_modules/babel-traverse/lib/path/context.js:48:17)
    at /Users/kross/projects/af_core/node_modules/happypack/lib/HappyLoader.js:41:23
    at /Users/kross/projects/af_core/node_modules/happypack/lib/HappyPlugin.js:314:7
    at /Users/kross/projects/af_core/node_modules/happypack/lib/HappyWorker.js:51:5
    at /Users/kross/projects/af_core/node_modules/happypack/lib/applyLoaders.js:270:18
    at /Users/kross/projects/af_core/node_modules/babel-loader/index.js:83:25
    at /Users/kross/projects/af_core/node_modules/babel-loader/lib/fs-cache.js:147:16
    at ReadFileContext.callback (/Users/kross/projects/af_core/node_modules/babel-loader/lib/fs-cache.js:28:23)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:359:13)
 @ ./ui/src/components/SignInForm.js 63:12-37
```

Any thoughts or strategies to shorten the syntax but get message generation working?

**Comment by ericf** [comment]
There won't be a change in the component or prop names anytime soon (or planned), and what you have is way too cryptic to be adopted by the library. Remember that code is read more than written, you might want to choose clarity over number of chars — even if just for your future self.

To resolve the compile error, pass along all the props to `<FormattedMessage>` instead of plucking off `v` and `m`.

You can also define your messages via the `defineMessages` API which this plugin also extracts from. The values have to be provided statically to one of the hooks, otherwise they won't be extracted.

Another option would be to just copy this source code and change it for what you want in to process things in your app,

**Comment by rosskevin** [comment]
Thank you very much for taking time to look at this and give me your thoughts and alternatives.

Some feedback (general on `react-intl`):

I've determined that `react-intl` is simply too verbose for our case.  We have a lot of translations interspersed with components (white-label core app).  We don't want the lengthy component **and** attribute names embedded in code; we find it very unreadable and distracting with the sheer volume of characters needed.  On our old server side code, we used `t()` for translation, and while cryptic, it was _incredibly obvious_ that we were translating a key (not to mention our IDE would also present the given translation inline).

Here is a comparison of approaches to achieve the same result of a typical interpolated string:
```javascript
// react-intl component
<p><FormattedMessage id="greeting" values={{name: name}} /></p>
// react-intl inject
<p>{intl.formatMessage({id: 'greeting'}, {name: name})}</p>
// i18next inject
<p>{t('greeting', {name: name})}</p>
```

While I think the `react-intl` appears to be quality code and very well maintained, the tax on the author is high and the developer joy is low.  i18n already has a low developer joy quotient, and I feel that this lengthy approach reminds you over and over of that.  

I will state again, this is not a reflection on the quality of the project, but I have to say that the **only** reason I am not going to use `react-intl` is because of the verbosity of usage.

Thanks again for putting this out there!

**Comment by ericf** [comment]
You know that with ES6 modules you can do this, right?

```js
import {FormattedMessage as T} from 'react-intl';
```

As for the prop names, I feel they follow idiomatic-React naming practices.

**Comment by rosskevin** [comment]
Yes, I understand you can alias in ES6+.

I agree, the current approach does follow idiomatic react naming practices.  As counterpoint, can you find any platform standard that would condone using `t()`?  `t()` on any other platform I am aware _does not_ follow the platform standards because anything longer is distracting from the point of the code.  The point is not to focus on translations, but the goal of the given codebase.

I'm not saying you shouldn't have the long versions for those that like to use them, but the short ones could be an option (quite easily it would seem).

In the source repo of `react-intl` itself, you are using shorter names for the files and exporting their internal long names.  Why would you use a non-idiomatic `message.js` instead of `formattedMessage.js` or `FormattedMessage.js`?  Perhaps the maintainers themselves grew tired of the long names!  I am being knowingly facetious, but that is a real example from the codebase and I think it does support my point.

**Comment by ericf** [comment]
Since I named the files, I can tell you, it was simply to avoid the case-sensitivity issues with filenames in Git.

The naming was crated to match with the declarative nature of React. `t()` means "to-translate", imperatively, whereas, `<FormattedMessage>` _is_ a message that's been formatted. This noun vs verb distinction is import.

It's possible that the `Formatted` prefix could be dropped, but even `<Message>` seems like it's too long for your situation in your app, as it would never be shorter than using `t()` with unnamed arguments.

**Comment by rosskevin** [comment]
> Since I named the files, I can tell you, it was simply to avoid the case-sensitivity issues with filenames in Git. In the actual source code the full names are always used.

So it appears that we indeed share the same philosophy, in that there are exceptions to idiomatic platform rules.

**Comment by ericf** [comment]
I generally agree with your generalization?
