### ISSUE TITLE
Add options to ignore non statically evaluate-able keys and values 

### ISSUE THREAD

**Issue by mike1808** [yahoo/babel-plugin-react-intl#62]
In my project I often use the following formatted message:
```jsx
<FormattedMessage id="id" defaultMessage="{value1} {value2}" values={{
  value1: (<FormattedMessage id={`common.${type}`} />),
  value2: (<FormattedMessage id={`common.${value}`} />),
}}/>
```

And during the messages extraction I'm getting `[React Intl] Messages must be statically evaluate-able for extraction.`. 

Can we have some option to ignore these messages and continue to extract?

**Comment by ericf** [comment]
In this case they should be ignored since there's no `defaultMessage`.
