### ISSUE TITLE
Add an option to include original line numbers within extracted message information

### ISSUE THREAD

**Issue by antoinepm** [yahoo/babel-plugin-react-intl#71]
Now that this plugin helps me extract the messages I need to translate (and it works great, thanks!), I am trying to generate a list of message-related issues (untranslated messages, etc.) further in my process. This is why I could use an additional "originalLineNumber" field in the extracted JSON data (or maybe "sourceLineNumber", or any other self-explaining name, of course). That information would let me find more quickly where, in the source code, the message is declared. Of course, the original file name would be useful too, but I can guess it from the JSON file path. And since not everybody is interested in the information, it could be made optional (maybe an "includeOriginalLineNumbers" option?).

Do you think it would be both possible and relevant?

A quick look at the plugin source code makes me think that the function storeMessage() could get the information from the property path.node.loc.start.line, when available. But then I may not be aware of some Babel subtleties.

**Comment by ericf** [comment]
Yeah this is totally possible to add. What do you want to consider as the start of the message being defined? I'm thinking it should be the nested object in `defineMessages()`, and the `<FormattedMessage>` element.

I think it makes sense to only save this information to the JSON files when an option is enabled on the Babel plugin.

**Comment by antoinepm** [comment]
I agree. Considering the nested object in `defineMessages()` and the `<FormattedMessage>` element itself as the start of each message being defined looks good to me.

**Comment by ericf** [comment]
@antoinepm I have something working. Let me know your thoughts on whether you want all of this data and if you think it should be structured differently. Here's an example:

```json
[
  {
    "id": "app.title",
    "defaultMessage": "React Intl Translations Example",
    "file": "src/client/components/app.js",
    "start": {
      "line": 23,
      "column": 20
    },
    "end": {
      "line": 26,
      "column": 22
    }
  },
  {
    "id": "app.locales_menu_heading",
    "defaultMessage": "Locales:",
    "file": "src/client/components/app.js",
    "start": {
      "line": 32,
      "column": 20
    },
    "end": {
      "line": 35,
      "column": 22
    }
  }
]
```

**Comment by antoinepm** [comment]
The data presented above looks great to me. Although I would use only some parts for my own purposes, I think that all of it should be included, as it is more self-explanatory than my initial suggestion. I like the extractSourceLocation parameter name, too.
Thanks!

**Comment by ericf** [comment]
Cool! I'll get this out soon… but maybe after the long weekend here in the US.

**Comment by antoinepm** [comment]
I see that the change has been published. Thanks a lot!
