### ISSUE TITLE
Trailing spaces are removed

### ISSUE THREAD

**Issue by Eschon** [yahoo/babel-plugin-react-intl#77]
I have the following code as part of my application:

``` JavaScript
<FormattedMessage id="TrackDetail.total" defaultMessage="total: " />
{total}
```

From this I get the following message:
``` JSON
{
  "id": "TrackDetail.total",
  "defaultMessage": "total:"
}
```

With the space removed I get the following output on my page:

```
total:1234
```

Instead of

```
total: 1234
```

I know that I could just write 

``` JavaScript
<FormattedMessage id="TrackDetail.total" defaultMessage="total:" /> {total}
```

as a workaround. But I don't like the look of that and I think that if I add a space in my default message it should still be there in the message-JSON.

**Comment by ericf** [comment]
Trimming is to prevent code-formatting changes to trigger retranslations (and cost) so insignificant whitespace is trimmed.

You might want your message to be written like:
```js
<FormattedMessage 
  id="TrackDetail.total" 
  defaultMessage="total: {total, number}" 
  values={{total: 1234}}
/>
```
And it will also format the number to `"1,234"`.

**Comment by Eschon** [comment]
Ok, thank you.

Writing the message like this makes sense.
