### ISSUE TITLE
Plugin doesn't seem to do anything

### ISSUE THREAD

**Issue by mschipperheyn** [yahoo/babel-plugin-react-intl#84]
Trying to get this to extract messages from my jsx files. My component sources are in ./src

	{
	  "presets": ["es2015", "stage-0", "react"],
	  "plugins": [
		["react-intl", {
			"messagesDir": "./i8n/messages/"
		}],
		"transform-decorators-legacy", "transform-runtime", "react-hot-loader/babel"]
	}

The cli command I use is 

    babel --plugins react-intl src/**/*.js

This seems to output a lot of js content of my files on screen, but nothing appears in my i8n/messages directory.

I would also expect on the fly output during development using webpack, but also doesn't happen.

Tried also 

    babel --plugins react-intl i8n/script.js 

with this script

	import * as p from 'path';
	import * as fs from 'fs';
	import {transformFileSync} from 'babel-core';
	import plugin from 'babel-plugin-react-intl';

	const baseDir = p.resolve(`${__dirname}/../src`);

	const fixtures = [
		'defineMessages',
		['extractSourceLocation', {
			extractSourceLocation: true,
		}],
		'FormattedHTMLMessage',
		'FormattedMessage',
		['moduleSourceName', {
			moduleSourceName: 'react-i18n',
		}],
	];

	fixtures.forEach((fixture) => {
		let name = fixture;
		let options = {};
		if (Array.isArray(fixture)) {
			[name, options] = fixture;
		}

		let {code, metadata} = transformFileSync(`${baseDir}/${name}/actual.js`, {
			plugins: [
				[plugin, {
					...options,
					messagesDir: false,
				}],
			],
		});

		let messages = JSON.stringify(metadata['react-intl'].messages, null, 2);

		fs.writeFileSync(`${baseDir}/${name}/expected.js`, `${code}\n`);
		fs.writeFileSync(`${baseDir}/${name}/expected.json`, `${messages}\n`);
	});

Also without apparent result other than a lot of javascript outputted on the screen.

Any suggestions?

**Comment by ericf** [comment]
This plugin does actually work. You can see from the tests in this repo and the `examples/translated` in the `react-intl` repo.

I'm not sure how to help with out a small project that shows the issue which can I run to reproduce. Feel free to re-open if it's still not working.
