### ISSUE TITLE
Overriding messages 

### ISSUE THREAD

**Issue by kishorevarma** [yahoo/babel-plugin-react-intl#9]
Hi,

When ever I run babel plugin  it actually overrides the existing translations(in messages folder), in my app I am translating messages from english to german. I might missing some point how to use this.

I am using some script to get all the messages from messages folder and write into a flat json file that I am using for intialising the <IntlProvider>

Please help me here how to get rid of this problem

**Comment by ericf** [comment]
This plugin is intended to extract your app's default language messages which then become the source input to your translation process.

I'm not sure I understand the problem you're having, can you explain more?
