### ISSUE TITLE
How do you treat longer text passage?

### ISSUE THREAD

**Issue by FredyC** [yahoo/babel-plugin-react-intl#98]
Some instructions text can be more then a single line. I like to use `common-tags` package with its`oneLine` template tag. Sadly this wont come through this plugin as it's not statically analyzable apparently :) 

```js
<FormattedMesssage
    id="description"
    defaultMessage={oneLine`
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed 
        do eiusmod tempor incididunt ut labore et dolore magna aliqua.
        Ut enim ad minim veniam, quis nostrud exercitation ullamco
        laboris nisi ut aliquip ex ea commodo consequat.
    `}
/>
```

Is there some other nice way or do I really need to have one long line there?

**Comment by ericf** [comment]
The message will be parsed as an ICU Message and then printed in a standard format, and on one line. This is to avoid unnecessary transition costs due to inconsequential formatting.

You should be able to remove the `oneLine` tag at the front of the template literal string and get what you want: multi-line in source and one-line in the extracted message.

**Comment by FredyC** [comment]
Well yes, there is a one line extracted, but it also contains line ends and tabs. 

> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed\n\t\tdo eiusmod tempor incididunt ut labore et dolore magna aliqua.

**Comment by ericf** [comment]
Did you give it a try? Does it result in what you were looking for?

**Comment by FredyC** [comment]
I know that these characters don't matter unless that text would be in <pre> (or similar). Texts are extracted with these characters and then I need to remove them before sending it for translation. It's not a huge deal obviously, but it could surely be better.

**Comment by ericf** [comment]
What about my questions above?

**Comment by FredyC** [comment]
Well that was kinda answer to your questions :) To be explicit, no it's not what I am looking for. I would like to have those messages extracted without line breaks and stuff.

**Comment by ericf** [comment]
They are extracted without line breaks. Did you try using the plugin to see what the result would be?

**Comment by FredyC** [comment]
Of course I tried the plugin and then went here because I did not like a result.

**Comment by ericf** [comment]
I see two approaches: 1) post process the messages to replace `\s` with a space 2) add an option to do this in the plugin's [ICU message printer](https://github.com/yahoo/babel-plugin-react-intl/blob/master/src/print-icu-message.js).

For the second option it'll likely be modal in that it would apply to every source message that's extracted.

**Comment by FredyC** [comment]
Could there be any actual use case where you want to keep `\s` in extracted messages? I am fairly new to whole intl stuff so I don't have enough experience to judge that. However since those messages are meant for a translation process by humans, a readability should be preferred in my opinion.
